// <auto-generated />
using FirstProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstProject.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20191007124836_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("FirstProject.Models.ogrenciler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("no")
                        .HasColumnType("TEXT");

                    b.Property<string>("soyad")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ogrencilers");
                });
#pragma warning restore 612, 618
        }
    }
}
